version: '3'
services:
  app:
    container_name: user-docker-sample
    build:
      context: .
    image: ahmedshakir/user-docker-sample:1.0
    ports:
      - 7000:7000
    depends_on:
      - db
    restart: always
  db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./datadir:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Password